### ISSUE TITLE
Mailing list?

### ISSUE THREAD

**Issue by andredasilvapinto** [kuujo/vertigo#16]
Is there any mailing list (or other form of public messaging) to which we can send our questions regarding Vertigo? I'm talking about usage questions, which I think perhaps should not be handled as an issue here on git hub...

Thanks.

**Comment by kuujo** [comment]
I am definitely going to start a mailing list this week. I don't think the Vert.x peeps want me cluttering up their Google group. I just have to get around to it :-)

I will post back here when I get it done!

**Comment by orolle** [comment]
Do you have a mailing list already?

**Comment by kuujo** [comment]
Indeed I do. I forgot to update this, but I updated the README page.

https://groups.google.com/forum/#!forum/vertx-vertigo
