### ISSUE TITLE
Remove the SNAPSHOT from pom.xml

### ISSUE THREAD

**Issue by sougatabh** [kuujo/vertigo#39]
Hi Jordon,
Please change 0.7.0-beta3-SNAPSHOT in pom.xml to 0.7.0-beta3.

Thanks
Sougata

**Comment by kuujo** [comment]
Why? beta3 is a release. The master branch is a snapshot until it's ready to be released via Maven. This is just how the Maven release plugin works.

Actually, I just released beta3 and it should be in Maven central next time it syncs. You should use the version in central if you want to use Vertigo 0.7.0-beta3
