### ISSUE TITLE
Refactor FieldsSelector.select method

### ISSUE THREAD

**Issue by andredasilvapinto** [kuujo/vertigo#4]
For

``` java
        hash += value.hashCode();
```

when value.hashCode() < 0

``` java
    int index = Integer.valueOf(hash) % connections.size();
```

will yield a negative value and trigger a IndexOutOfBoundsException in the following line:

``` java
    return connections.subList(index, index+1);
```

Also, when we have multiple fieldNames we will probably get errors on Integer.valueOf(hash) as the string may not be a valid Integer. This can occur either by overflow (multiple positive hashs concatenated) or invalid numbers (imagine "1000000000" and "-1000000000" hashes).

Finally, if you are going to concatenate Strings on a loop, it's better to use a StringBuilder instead of the += operator. StringBuilder doesn't need to keep creating new String objects every time you append a new String to it.

**Comment by kuujo** [comment]
Right on all counts. Excellent!

^^ merged ^^

**Comment by andredasilvapinto** [comment]
Thanks
